// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealtimeLeaderboardAPI.Infrastructure;

#nullable disable

namespace Real_timeLeaderboardAPI.Migrations
{
    [DbContext(typeof(RealtimeLeaderboardAPIDbContext))]
    [Migration("20260722161235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealtimeLeaderboardAPI.Domain.ArchivedLeaderboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("FinalRankingScore")
                        .HasColumnType("double precision");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("GameTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Place")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ArchivedLeaderboardTable");
                });

            modelBuilder.Entity("RealtimeLeaderboardAPI.Domain.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("GameTable");
                });

            modelBuilder.Entity("RealtimeLeaderboardAPI.Domain.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokenTable");
                });

            modelBuilder.Entity("RealtimeLeaderboardAPI.Domain.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentRankingScore")
                        .HasColumnType("double precision");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<double>("HighestRankingScore")
                        .HasColumnType("double precision");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SeasonId", "UserId")
                        .IsUnique();

                    b.ToTable("ScoreTable", t =>
                        {
                            t.HasCheckConstraint("CK_Score_CurrentRankingScore_NonNegative", "\"CurrentRankingScore\" >= 0");

                            t.HasCheckConstraint("CK_Score_HighestRankingScore_NonNegative", "\"HighestRankingScore\" >= 0");
                        });
                });

            modelBuilder.Entity("RealtimeLeaderboardAPI.Domain.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("Name", "GameId")
                        .IsUnique();

                    b.ToTable("SeasonTable", t =>
                        {
                            t.HasCheckConstraint("CK_SeasonTable_SeasonStatus", "\"SeasonStatus\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("RealtimeLeaderboardAPI.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserTable");
                });

            modelBuilder.Entity("RealtimeLeaderboardAPI.Domain.Score", b =>
                {
                    b.HasOne("RealtimeLeaderboardAPI.Domain.Season", "Season")
                        .WithMany("ScoreRisuto")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealtimeLeaderboardAPI.Domain.User", "User")
                        .WithMany("ScoreRisuto")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealtimeLeaderboardAPI.Domain.Season", b =>
                {
                    b.HasOne("RealtimeLeaderboardAPI.Domain.Game", "Game")
                        .WithMany("SeasonRisuto")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("RealtimeLeaderboardAPI.Domain.Game", b =>
                {
                    b.Navigation("SeasonRisuto");
                });

            modelBuilder.Entity("RealtimeLeaderboardAPI.Domain.Season", b =>
                {
                    b.Navigation("ScoreRisuto");
                });

            modelBuilder.Entity("RealtimeLeaderboardAPI.Domain.User", b =>
                {
                    b.Navigation("ScoreRisuto");
                });
#pragma warning restore 612, 618
        }
    }
}
